name: Multiple shells commands
on:
  push:
    branches:
      - main
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python commands
        run: |
          python3 -c "import platform; print(platform.processor())"

  run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Current directory with PowerShell
        run: Get-Location
        shell: pwsh
      - name: Print current directory with Bash
        run: pwd
        shell: bash
      - name: Print default GitHub environment variables
        run: |
          echo "HOME: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
